**Jumaih Barakat**
 **WTF/2025/2154**
 **jumaihbarakat014@outlook.com**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
HR=pd.read_csv("/content/drive/MyDrive/hiring (1).csv")
HR

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
HR.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [ ]:
HR.isna()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        True                  False                       False      False
1        True                  False                       False      False
2       False                  False                       False      False
3       False                  False                       False      False
4       False                  False                       False      False
5       False                  False                       False      False
6       False                   True                       False      False
7       False                  False                       False      False

In [ ]:
HR.isna().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [ ]:
HR.shape

(8, 4)

In [ ]:
HR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes


In [ ]:
HR['test_score(out of 10)'].fillna(HR['test_score(out of 10)'].mean(),inplace=True)
HR

/tmp/ipython-input-3438657349.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  HR['test_score(out of 10)'].fillna(HR['test_score(out of 10)'].mean(),inplace=True)


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN               8.000000                           9      50000
1        NaN               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [ ]:
HR['experience'].fillna('Not specified')

0      Zero
1      Zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [ ]:
HR.head(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [ ]:
 #Define a mapping for experience words to numerical values
word_to_num = {
    'Zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,
    'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10, 'eleven': 11
}


In [ ]:
HR['experience'] = df_for_fit['experience']

In [ ]:
# Fill NaN values in 'experience' with 'Zero' before mapping
df_for_fit['experience'] = df_for_fit['experience'].fillna('zero')

# Apply the mapping to the 'experience' column, updating the column within the DataFrame
df_for_fit['experience'] = df_for_fit['experience'].map(word_to_num)

In [ ]:

HR['test_score(out of 10)'].fillna(HR['test_score(out of 10)'].mean(),inplace=True)


# Create a fresh copy of HR to ensure it reflects the latest state (e.g., filled test_score)
df_for_fit = HR.copy()

#defining the experience into a numerical value
word_to_num = {
    'Zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,
    'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10, 'eleven': 11
}

# Fill NaN values in 'experience' with 'Zero' string, matching the word_to_num dictionary key
df_for_fit['experience'].fillna('Zero', inplace=True)

# Applying the mapping to convert word experience to numerical
df_for_fit['experience'] = df_for_fit['experience'].map(word_to_num)



In [ ]:
reg = linear_model.LinearRegression()
reg

LinearRegression()

In [ ]:
## fit the model with the prepared data
reg.fit(df_for_fit.drop("salary($)",axis= "columns"), df_for_fit['salary($)'])

LinearRegression()

In [ ]:
reg.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [ ]:
reg.intercept_

np.float64(17237.330313727172)

In [ ]:
reg.score(df_for_fit.drop("salary($)",axis= "columns"), df_for_fit['salary($)'])

0.9639958361860579

In [ ]:
#SALARY PREDICTION FOR CANDIDATE WITH 2YRS EXPERIENCE,9 TEST SCORE AND 6 INTERVIEW SCORE
reg.predict([[2,9,6]])

array([53290.89255945])

In [ ]:
#SALARY PREDICTION FOR CANDIDATE WITH 12YRS EXPERIENCE, 10 TEST SCORE AND 10 INTERVIEW SCORE
reg.predict([[12,10,10]])

array([92268.07227784])